In [ ]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

In [31]:
ann_ihd = pd.read_csv('results/annual_results_IHD.csv')
ann_all = pd.read_csv('results/annual_results_all.csv')

gdp = pd.read_csv('data/GDP_ppp.csv')
gdp

,Country Code,2010,2011,2012,2013,2014,2015,2016,2017,2018,...,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050
0,ABW,3.491496e+09,3.611815e+09,3.562338e+09,3.711894e+09,3.723029e+09,3.935242e+09,4.017882e+09,4.098240e+09,4.098240e+09,...,5.521483e+09,5.635380e+09,5.751627e+09,5.870271e+09,5.991363e+09,6.114953e+09,6.241092e+09,6.369834e+09,6.501230e+09,6.635338e+09
1,AFG,5.711689e+10,5.736041e+10,6.467518e+10,6.829747e+10,7.015826e+10,7.117648e+10,7.278529e+10,7.471192e+10,7.560042e+10,...,8.393724e+10,8.576707e+10,8.763679e+10,8.954727e+10,9.149940e+10,9.349409e+10,9.553226e+10,9.761487e+10,9.974287e+10,1.019173e+11
2,AGO,1.796660e+11,1.859040e+11,2.017850e+11,2.117820e+11,2.219960e+11,2.240900e+11,2.183090e+11,2.179870e+11,2.136200e+11,...,2.108629e+11,2.089685e+11,2.070911e+11,2.052306e+11,2.033868e+11,2.015596e+11,1.997488e+11,1.979543e+11,1.961758e+11,1.944134e+11
3,ALB,3.131347e+10,3.211052e+10,3.256560e+10,3.289192e+10,3.347557e+10,3.421830e+10,3.535263e+10,3.669682e+10,3.817179e+10,...,6.981139e+10,7.196758e+10,7.419037e+10,7.648182e+10,7.884403e+10,8.127921e+10,8.378960e+10,8.637753e+10,8.904538e+10,9.179564e+10
4,ARE,4.695810e+11,5.021160e+11,5.246300e+11,5.511400e+11,5.754460e+11,6.045650e+11,6.226070e+11,6.373850e+11,6.449690e+11,...,1.121289e+12,1.155249e+12,1.190237e+12,1.226284e+12,1.263423e+12,1.301687e+12,1.341110e+12,1.381727e+12,1.423574e+12,1.466689e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,VUT,7.296662e+08,7.525622e+08,7.601633e+08,7.637255e+08,7.876015e+08,7.905280e+08,8.275933e+08,8.798609e+08,9.053789e+08,...,1.568409e+09,1.623347e+09,1.680210e+09,1.739064e+09,1.799980e+09,1.863030e+09,1.928288e+09,1.995832e+09,2.065742e+09,2.138101e+09
183,WSM,1.117539e+09,1.163399e+09,1.115880e+09,1.112060e+09,1.112640e+09,1.160449e+09,1.254750e+09,1.267830e+09,1.252195e+09,...,2.059999e+09,2.128325e+09,2.198917e+09,2.271851e+09,2.347203e+09,2.425056e+09,2.505490e+09,2.588592e+09,2.674450e+09,2.763156e+09
184,ZAF,6.975100e+11,7.196110e+11,7.368540e+11,7.551690e+11,7.658450e+11,7.759690e+11,7.811260e+11,7.901710e+11,8.019250e+11,...,9.111122e+11,9.197605e+11,9.284909e+11,9.373041e+11,9.462010e+11,9.551823e+11,9.642489e+11,9.734016e+11,9.826411e+11,9.919683e+11
185,ZMB,4.252590e+10,4.489230e+10,4.830303e+10,5.074583e+10,5.312986e+10,5.468146e+10,5.674660e+10,5.873519e+10,6.110486e+10,...,1.157219e+11,1.193502e+11,1.230923e+11,1.269518e+11,1.309322e+11,1.350375e+11,1.392714e+11,1.436381e+11,1.481418e+11,1.527866e+11
186,ZWE,3.617683e+10,4.131174e+10,4.819652e+10,4.915539e+10,5.032378e+10,5.121948e+10,5.160663e+10,5.403704e+10,5.664390e+10,...,7.022683e+10,7.104750e+10,7.187776e+10,7.271772e+10,7.356750e+10,7.442721e+10,7.529697e+10,7.617689e+10,7.706709e+10,7.796770e+10

In [49]:
usa_df = ann_all[(ann_all['Country Code'] == 'USA') & (ann_all['scenario'] == 'val')].sort_values('year').copy()
usa_df

,year,GDP_loss_percapita,GDP_loss,GDP_loss_percentage,EffectiveLabor_loss_percentage,disease,Country Code,scenario,ConsiderTC,ConsiderMB,informal,discount
31279,2020,16.055123,5.314288e+09,0.000268,0.000443,Ischemic heart disease,USA,val,1,1,0.0,0.02
40269,2020,0.495693,1.640755e+08,0.000008,0.000014,Lower extremity peripheral arterial disease,USA,val,1,1,0.0,0.02
35774,2020,6.638177,2.197254e+09,0.000111,0.000183,Ischemic stroke,USA,val,1,1,0.0,0.02
31280,2021,41.900913,1.394945e+10,0.000742,0.000975,Ischemic heart disease,USA,val,1,1,0.0,0.02
40270,2021,1.679931,5.592745e+08,0.000030,0.000021,Lower extremity peripheral arterial disease,USA,val,1,1,0.0,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...
31308,2049,399.766082,1.512046e+11,0.007245,0.004992,Ischemic heart disease,USA,val,1,1,0.0,0.02
40298,2049,24.630393,9.316019e+09,0.000446,0.000112,Lower extremity peripheral arterial disease,USA,val,1,1,0.0,0.02
35804,2050,169.045774,6.413919e+10,0.003063,0.001708,Ischemic stroke,USA,val,1,1,0.0,0.02
31309,2050,405.046384,1.536823e+11,0.007340,0.004991,Ischemic heart disease,USA,val,1,1,0.0,0.02
40299,2050,25.162938,9.547299e+09,0.000456,0.000115,Lower extremity peripheral arterial disease,USA,val,1,1,0.0,0.02

In [47]:
usa_df

    year      GDP_loss
0   2019  0.000000e+00
1   2020  7.675618e+09
2   2021  1.909554e+10
3   2022  3.465261e+10
4   2023  4.815611e+10
5   2024  6.001556e+10
6   2025  7.274687e+10
7   2026  8.082357e+10
8   2027  9.021712e+10
9   2028  9.784532e+10
10  2029  1.055471e+11
11  2030  1.136480e+11
12  2031  1.207522e+11
13  2032  1.284682e+11
14  2033  1.352997e+11
15  2034  1.418447e+11
16  2035  1.486477e+11
17  2036  1.546654e+11
18  2037  1.610477e+11
19  2038  1.668996e+11
20  2039  1.726265e+11
21  2040  1.784216e+11
22  2041  1.836901e+11
23  2042  1.892302e+11
24  2043  1.943649e+11
25  2044  1.994254e+11
26  2045  2.044609e+11
27  2046  2.092048e+11
28  2047  2.139254e+11
29  2048  2.185254e+11
30  2049  2.229081e+11
31  2050  2.273688e+11

In [33]:
usa_df = ann_all[(ann_all['Country Code'] == 'USA') & (ann_all['scenario'] == 'val')].sort_values('year').copy()
usa_df = usa_df.groupby('year')['GDP_loss'].sum().reset_index()
usa_df = pd.concat([pd.DataFrame({'year': [2019], 'GDP_loss': [0]}), usa_df], ignore_index=True)

gdp_years = [str(y) for y in range(2019, 2051)]
usa_gdp = gdp[gdp['Country Code'] == 'USA'].copy()
usa_gdp = usa_gdp[gdp_years].T.reset_index()
usa_gdp.columns = ['year', 'GDP_SQ']
usa_gdp['year'] = usa_gdp['year'].astype(int)

usa = usa_df.merge(usa_gdp, on='year', how='left')
usa['GDP_CF'] = usa['GDP_loss'] + usa['GDP_SQ']

usa

    year      GDP_loss        GDP_SQ        GDP_CF
0   2019  0.000000e+00  2.056360e+13  2.056360e+13
1   2020  7.675618e+09  1.986350e+13  1.987118e+13
2   2021  1.909554e+10  1.918715e+13  1.920624e+13
3   2022  3.465261e+10  2.027640e+13  2.031105e+13
4   2023  4.815611e+10  2.102825e+13  2.107641e+13
5   2024  6.001556e+10  2.150139e+13  2.156140e+13
6   2025  7.274687e+10  2.181058e+13  2.188332e+13
7   2026  8.082357e+10  2.217721e+13  2.225804e+13
8   2027  9.021712e+10  2.255423e+13  2.264444e+13
9   2028  9.784532e+10  2.293765e+13  2.303549e+13
10  2029  1.055471e+11  2.348072e+13  2.358627e+13
11  2030  1.136480e+11  2.403665e+13  2.415030e+13
12  2031  1.207522e+11  2.460574e+13  2.472649e+13
13  2032  1.284682e+11  2.518831e+13  2.531677e+13
14  2033  1.352997e+11  2.578466e+13  2.591996e+13
15  2034  1.418447e+11  2.639514e+13  2.653699e+13
16  2035  1.486477e+11  2.702007e+13  2.716872e+13
17  2036  1.546654e+11  2.765980e+13  2.781447e+13
18  2037  1.610477e+11  2.831467e+13  2.847572e+13
19  2038  1.668996e+11  2.898505e+13  2.915195e+13
20  2039  1.726265e+11  2.967130e+13  2.984393e+13
21  2040  1.784216e+11  3.037380e+13  3.055222e+13
22  2041  1.836901e+11  3.109293e+13  3.127662e+13
23  2042  1.892302e+11  3.182909e+13  3.201832e+13
24  2043  1.943649e+11  3.258267e+13  3.277704e+13
25  2044  1.994254e+11  3.335410e+13  3.355352e+13
26  2045  2.044609e+11  3.414379e+13  3.434825e+13
27  2046  2.092048e+11  3.495218e+13  3.516138e+13
28  2047  2.139254e+11  3.577971e+13  3.599363e+13
29  2048  2.185254e+11  3.662683e+13  3.684535e+13
30  2049  2.229081e+11  3.749400e+13  3.771691e+13
31  2050  2.273688e+11  3.838171e+13  3.860908e+13

In [ ]:
import matplotlib.pyplot as plt

In [45]:
usa_sq = usa[['GDP_SQ']].values.flatten() / 1e6
usa_cf = usa[['GDP_CF']].values.flatten() / 1e6

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=list(range(2019, 2051)),
    y=usa_sq,
    mode='lines+markers',
    marker=dict(size=4),
    line=dict(width=2),
    name='USA GDP (PPP)'
))
fig.add_trace(go.Scatter(
    x=list(range(2019, 2051)),
    y=usa_cf,
    mode='lines+markers',
    marker=dict(size=4),
    line=dict(width=2),
    name='USA GDP (PPP)'
))

fig.update_layout(
    width=600,
    height=400,
    xaxis_title='Year',
    yaxis_title='GDP (trillions of 2017 INT$)',
    template='plotly_white',
    font=dict(family='Helvetica', size=10),
    margin=dict(l=60, r=20, t=40, b=40),
)
fig.show()